### PR TITLE
Update Styling To Match Homepage

### PR DESCRIPTION
**Pull request by vmitchell85**
I've updated the styling to match the homepage. Removed bootstrap and jQuery and importing Prism JS for code styling.

image

### CODE REVIEW

**Comment by vmitchell85** [comment]
Looks like there is a formatting issue with the code blocks... will look into it...

**Comment by JacobBennett** [comment]
Looking great @vmitchell85! Thank you!

**Comment by JacobBennett** [comment]
Hey @vmitchell85 sorry for not getting to this sooner, hoping to take a look tonight. Thank you for your hard work!

**Comment by vmitchell85** [comment]
no problem... I used the hero pattern mentioned in #2 but can switch to the `bgpattern.png` if desired...

Also #6 looked great also... not sure why @wilburpowery closed it... I won't be offended if you choose his over mine 😉

**Comment by wilburpowery** [comment]
@vmitchell85 I closed it because I did not notice you had already made a PR about the stuff. 😄 

I guess @JacobBennett can have a look at both and give his feedback. I'll be happy to help with anything 😃

**Comment by vmitchell85** [comment]
Closing since there is no action being taken

**Pull request closed without merging**
